Timbi/Controllers/AdminPanelController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Timbi.ViewModels;
using Timbi.Data.Models;
using Microsoft.AspNetCore.Identity;
using System.Linq;

namespace Timbi.Controllers
{
    public class AdminPanelController : Controller
    {
        UserManager<User> _userManager;

        public AdminPanelController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Year = model.Year };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }


        public async Task<IActionResult> ChangePasswordUser(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordUserViewModel model = new ChangePasswordUserViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> ChangePasswordUser(ChangePasswordUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result =
                        await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }

        public IActionResult Company() => View();
    }
}

Timbi/Controllers/UserAreaController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.Linq;
using Timbi.Data.Models;
using Timbi.Data.Interfaces;
using Timbi.ViewModels;

namespace Timbi.Controllers
{
    public class UserAreaController : Controller
    {
        private readonly IAllUserArea IAllUserArea;
        public UserAreaController(IAllUserArea _IAllUserArea)
        {
            IAllUserArea = _IAllUserArea;
        }



        [HttpPost]
        public IActionResult Index()
        {
            UserAreaViewModel UserArea = new UserAreaViewModel();

            UserArea.Regions = IAllUserArea.Region;

            return View(UserArea);
        }
    }
}

Timbi/Views/Shared/AllCompany.cshtml
@model Company


<div class="col - lg - 2" style="border: thin solid black">
    
        <input type="image" src="~/img/CompanyIcon/gaz.jpg" alt="@Model.NameCompany" />
        <h2 align="center">@Model.NameCompany</h2>
       <p><a class="btn btn-warning" asp-controller="Connect" asp-action="ConnectPage" asp-route-id="@Model.NameCompany">Добавить в корзину</a></p>
    
    
    @*<button formmethod="post" asp-controller="Connect" asp-action="ConnectPage" asp-route-company="@Model.NameCompany"  >  OK   </button>*@
    
    
    
   
</div>

Timbi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <!--<title>@ViewBag.Title</title>-->
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style.css" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



</head>
<body>
    <header>
        <!--<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">-->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            @*<a class="navbar-brand" href="#">Tambi</a>*@
            <a class="navbar-brand" ></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="start" asp-action="startpage">Главная <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="connect" asp-action="connectpage">Подключение <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="cooperation" asp-action="cooperationpage">Сотрудничество <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="contact" asp-action="contactpage">Контакты<span class="sr-only">(current)</span></a>
                    </li>

                    @if (String.Compare(User.Identity.Name, "serg.mariupolcity@gmail.com", StringComparison.OrdinalIgnoreCase) == 0)
                    {
                        <li class="nav-item active">
                            @*Adminka*@
                            <a class="nav-link" asp-controller="AdminPanel" asp-action="Index">Админ панель <span class="sr-only">(current)</span></a>
                        </li>
                    }

                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <form class="form-inline mt-2 mt-md-0 mr-2" method="post" asp-controller="UserArea" asp-action="Index">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Личный кабинет</button>
                    </form>

                    <form class="form-inline mt-2 mt-md-0 mr-2" method="post" asp-controller="Account" asp-action="Logout">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Выход</button>
                    </form>
                }
                else
                {
                    <form class="form-inline mt-2 mt-md-0 mr-2" method="get" asp-controller="Account" asp-action="Register">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Register</button>
                    </form>

                    <form class="form-inline mt-2 mt-md-0 mr-2" method="post" asp-controller="Account" asp-action="Login">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Войти</button>
                    </form>
                }
            </div>
            <p></p>



        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2017-2019 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>
    <script>src = "~/js/Bootstrap.min.js"</script>
</body>
</html>